€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\classes\routes.py", line 110, in view_class
    return render_template('class/view_class.html', lesson=lesson, academy=academy, expected=expected_progress, actual_progress=actual_progress)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Diana\pythonWorkspace\academy\app\templates\class\view_class.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Diana\pythonWorkspace\academy\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\Diana\pythonWorkspace\academy\app\templates\base.html", line 61, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\Diana\pythonWorkspace\academy\app\templates\class\view_class.html", line 43, in block "app_content"
    {% include '_updateprogress.html' %}
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Diana\pythonWorkspace\academy\app\templates\_updateprogress.html", line 25, in template
    <td>{{ render_field(attendance.attended, id="attended-" + {{ student.id }}, class='form-control', style="width:5%;") }}</td>
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:86]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\classes\routes.py", line 112, in view_class
    update_form = StepProgressForm()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 473, in __init__
    super(SelectField, self).__init__(label, validators, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 442, in __init__
    super(SelectFieldBase, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:86]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\classes\routes.py", line 112, in view_class
    update_form = StepProgressForm()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_wtf\form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 268, in __init__
    super(Form, self).__init__(self._unbound_fields, meta=meta_obj, prefix=prefix)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\form.py", line 51, in __init__
    field = meta.bind_field(self, unbound_field, options)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\meta.py", line 27, in bind_field
    return unbound_field.bind(form=form, **options)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 376, in bind
    return self.field_class(*self.args, **kw)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 473, in __init__
    super(SelectField, self).__init__(label, validators, **kwargs)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\wtforms\fields\core.py", line 442, in __init__
    super(SelectFieldBase, self).__init__(label, validators, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'validator'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:86]
