€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\classes\routes.py", line 482, in no_show
    return redirect(url_for('classes.view_class', name=lesson.name, academy=academy.name))
NameError: name 'academy' is not defined
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\models.py", line 208, in check_auth
    return func (*args, **kwargs)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\main\routes.py", line 33, in make_announcement
    return render_template('make_announcement.html', title='Make Announcement', form=form)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: make_announcement.html
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\models.py", line 208, in check_auth
    return func (*args, **kwargs)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\main\routes.py", line 54, in make_announcement
    return redirect(url_for('index'))
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
€(asctime)s €(levelname)s: €(message)s [in €pathnames:92]
