€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\models.py", line 209, in check_auth
    return func (*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 243, in edit_student
    if acad.name != 'Online' and acad.name != academy.name:
AttributeError: 'NoneType' object has no attribute 'name'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\models.py", line 209, in check_auth
    return func (*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 254, in edit_student
    upper_limit = form2.step_.data + 2
TypeError: can only concatenate str (not "int") to str
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\models.py", line 209, in check_auth
    return func (*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 256, in edit_student
    if  form2.step_.data < lower_limit or form2.step_.data > upper_limit:
TypeError: '<' not supported between instances of 'str' and 'int'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 128, in student_profile
    additional_class_1=additional_class_1,
NameError: name 'additional_class_1' is not defined
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\diana\pythonworkspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Diana\pythonWorkspace\academy\app\students\routes.py", line 116, in student_profile
    if lesson.typeofclass.name == 'Group General English':
AttributeError: 'Lessons' object has no attribute 'typeofclass'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:89]
