€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\staff\routes.py", line 25, in user
    files = os.listdir(current_app.config['UPLOAD_PATH'] + 'avatars')
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\kwssw\\OneDrive\\Documentos\\Workspace\\academy\\app/static/uploads/avatars'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\models.py", line 212, in check_auth
    return func (*args, **kwargs)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\classes\routes.py", line 349, in insert_custom
    custom = CustomInsert(
NameError: name 'CustomInsert' is not defined
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
€(asctime)s €(levelname)s: €(message)s [in €pathnames:1891]
Traceback (most recent call last):
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\classes\routes.py", line 254, in view_class
    return render_template(
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\templates\class\view_class.html", line 3, in top-level template code
    {% from "_attendancehelper.html" import render_field %}
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\templates\base.html", line 65, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\kwssw\OneDrive\Documentos\Workspace\academy\app\templates\class\view_class.html", line 39, in block "app_content"
    <b>Inserted By:</b> {{ custom_progress.user.name }}
  File "c:\users\kwssw\onedrive\documentos\workspace\academy\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.CustomInsert object' has no attribute 'user'
€(asctime)s €(levelname)s: €(message)s [in €pathnames:95]
